<a href="https://colab.research.google.com/github/shreyasnarke/DataAnalytics/blob/main/imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Read The dataset

In [ ]:
import pandas as pd
import numpy as np
#Load a real-world dataset
df=pd.read_csv("/education.csv")
df=df.iloc[0:10]
print(df)
#Read first 5 Rows
#print(df.head())
#Describe Data
#print(df.describe())
#find Null Values
print(df.isna().sum())

   datasrno  workex  gmat
0         1      21   720
1         2     107   640
2         3      57   740
3         4      99   690
4         5     208   710
5         6     136   660
6         7      70   660
7         8     103   710
8         9      79   700
9        10      22   730
datasrno    0
workex      0
gmat        0
dtype: int64


In [ ]:
#create a randome mask with the same shape as the original dataset
x=np.random.rand(df.shape[0],df.shape[1])
print(x)
mask=x>0.8
print(mask)
#Apply the Mask to the original dataset to create missing data
df_missing=df.copy()
df_missing[mask]=np.nan
print("original data")
print(df)
print("Missing data")
print(df_missing)
print(df_missing.isna().sum())
#write a new file
df_missing.to_csv("education_missing.csv",index=False)

[[0.8036643  0.75203373 0.77921432]
 [0.79384429 0.53583548 0.96421279]
 [0.74129654 0.71947446 0.14549117]
 [0.91300906 0.54117707 0.49432295]
 [0.14425777 0.41721735 0.32119863]
 [0.53864491 0.16637165 0.9943148 ]
 [0.18063172 0.2652772  0.66768985]
 [0.11590502 0.95408991 0.79395502]
 [0.37747037 0.21760309 0.09759635]
 [0.7107527  0.45704411 0.1708603 ]]
[[ True False False]
 [False False  True]
 [False False False]
 [ True False False]
 [False False False]
 [False False  True]
 [False False False]
 [False  True False]
 [False False False]
 [False False False]]
original data
   datasrno  workex  gmat
0         1      21   720
1         2     107   640
2         3      57   740
3         4      99   690
4         5     208   710
5         6     136   660
6         7      70   660
7         8     103   710
8         9      79   700
9        10      22   730
Missing data
   datasrno  workex   gmat
0       NaN    21.0  720.0
1       2.0   107.0    NaN
2       3.0    57.0  740.0
3      

Imputation

In [ ]:
import pandas as pd
import numpy as np
#Load a real-world dataset
df_missing=pd.read_csv("/content/education_missing.csv")
print(df_missing)
#replace nan values with the mean of thecolumn
data_mean=df_missing.fillna(df_missing.mean())
print("replace nan values with the mean of thecolumn")
print(data_mean)
#replace nan values with the median of the column
data_median=df_missing.fillna(df_missing.median())
print(data_median)
#

   datasrno  workex   gmat
0       NaN    21.0  720.0
1       2.0   107.0    NaN
2       3.0    57.0  740.0
3       NaN    99.0  690.0
4       5.0   208.0  710.0
5       6.0   136.0    NaN
6       7.0    70.0  660.0
7       8.0     NaN  710.0
8       9.0    79.0  700.0
9      10.0    22.0  730.0
replace nan values with the mean of thecolumn
   datasrno      workex   gmat
0      6.25   21.000000  720.0
1      2.00  107.000000  707.5
2      3.00   57.000000  740.0
3      6.25   99.000000  690.0
4      5.00  208.000000  710.0
5      6.00  136.000000  707.5
6      7.00   70.000000  660.0
7      8.00   88.777778  710.0
8      9.00   79.000000  700.0
9     10.00   22.000000  730.0
   datasrno  workex   gmat
0       6.5    21.0  720.0
1       2.0   107.0  710.0
2       3.0    57.0  740.0
3       6.5    99.0  690.0
4       5.0   208.0  710.0
5       6.0   136.0  710.0
6       7.0    70.0  660.0
7       8.0    79.0  710.0
8       9.0    79.0  700.0
9      10.0    22.0  730.0


Data Discretization

In [14]:
import pandas as pd
import numpy as np
#Load a real-world dataset
df=pd.read_csv("/education.csv")
df=df.iloc[0:6]
#extract work exp col
workex=df["workex"]
#define bin range and lebles
bin_edges=[0,50,100,150]
bin_names=["low","medium","high"]
#create new col for discretized variable
df["median_exp_binned"]=pd.cut(workex,bins=bin_edges,labels=bin_names)
print(df.head())

   datasrno  workex  gmat median_exp_binned
0         1      21   720               low
1         2     107   640              high
2         3      57   740            medium
3         4      99   690            medium
4         5     208   710               NaN


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Min-Max Scaling

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
df=pd.read_csv("/education.csv")
df1=df.iloc[0:6]
scalar=MinMaxScaler()
df1_scaled=scalar.fit_transform(df1)
print(df1)
print(df1_scaled)

   datasrno  workex  gmat
0         1      21   720
1         2     107   640
2         3      57   740
3         4      99   690
4         5     208   710
5         6     136   660
[[0.         0.         0.8       ]
 [0.2        0.45989305 0.        ]
 [0.4        0.19251337 1.        ]
 [0.6        0.4171123  0.5       ]
 [0.8        1.         0.7       ]
 [1.         0.61497326 0.2       ]]
